namespace NotaSys.Models.Enums {
    public enum UfEnum {
        Acre = 12,
        Alagoas = 27,
        Amapa = 16,
        Amazonas = 13,
        Bahia = 29,
        Ceara = 23,
        DistritoFederal = 53,
        EspiritoSanto = 32,
        Goias = 52,
        Maranhao = 21,
        MatoGrosso = 51,
        MatoGrossoDoSul = 50,
        MinasGerais = 31,
        Para = 15,
        Paraiba = 25,
        Parana = 41,
        Pernambuco = 26,
        Piauí = 22,
        RioGrandedoNorte = 24,
        RioGrandedoSul = 43,
        RiodeJaneiro = 33,
        Rondonia = 11,
        Roraima = 14,
        SantaCatarina = 42,
        SaoPaulo = 35,
        Sergipe = 28,
        Tocantins = 17
    }
}
