// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaSys.Context;

#nullable disable

namespace NotaSys.Migrations
{
    [DbContext(typeof(NotaSysContext))]
    partial class NotaSysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotaSys.Models.Arquivo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArquivoXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadeFederativa")
                        .HasColumnType("int");

                    b.Property<int>("nNf")
                        .HasColumnType("int");

                    b.Property<int>("serie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
